version: '3.8'

services:

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://platform-api
    restart: unless-stopped

  # Platform Backend
  platform-postgres:
    image: postgres:15
    container_name: platform_postgres
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform
    volumes:
      - platform_postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  platform-api:
    build:
      context: backend
      dockerfile: ./Platform/Dockerfile
    container_name: platform-api
    depends_on:
      - platform-postgres
    environment:
      # Base
      ASPNETCORE_URLS: http://+:80\
      ASPNETCORE_ENVIRONMENT: Development

      # DB
      Database__ConnectionString: "User ID=platform;Password=platform;Host=platform-postgres;Port=5432;Database=platform;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Idle Lifetime=60;"
      Database__DatabaseProvider: PostgreSql

      # Rmq
      RabbitMQ__Nodes__0: rabbitmq
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123
      RabbitMQ__VirtualHost: /
      RabbitMQ__NeedToPrepare: true

      # External Api
      BankManager__ServerUrl: "http://bank-manager-api"

      # AWS
      AWS__Region: "us-east-1"
      AWS__ServiceURL: "http://minio:9000/"
      AWS__AccessKey: minio
      AWS__SecretKey: minio123
      AWS__BucketName: files
      AWS__NeedToEnsureBucketExists: true

      ## Ffmpeg
      Video__FFmpegBinaryFolder: /usr/bin
    ports:
      - "5001:80"
    networks:
      - app-net


# Bank Manager Backend
  bank-manager-postgres:
    image: postgres:15
    container_name: bank_manager_postgres
    environment:
      POSTGRES_DB: bank_manager
      POSTGRES_USER: bank_manager
      POSTGRES_PASSWORD: bank_manager
    volumes:
      - bank_manager_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  bank-manager-api:
    build:
      context: backend
      dockerfile: ./BankManager/Dockerfile
    container_name: bank-manager-api
    depends_on:
      - bank-manager-postgres
    environment:
      # Base
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development

      # DB
      Database__ConnectionString: "User ID=bank_manager;Password=bank_manager;Host=bank-manager-postgres;Port=5432;Database=bank_manager;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Idle Lifetime=60;"
      Database__DatabaseProvider: PostgreSql

      # Rmq
      RabbitMQ__Nodes__0: rabbitmq
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123
      RabbitMQ__VirtualHost: /
      RabbitMQ__NeedToPrepare: true
    ports:
      - "5002:80"
    networks:
      - app-net


# TODO Frontend, Jobs

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq123
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio-local
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
        MINIO_ROOT_USER: minio     # ← Измените здесь
        MINIO_ROOT_PASSWORD: minio123  # ← И здесь
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-net


  # postgres-db-old:
  #   image: postgres:16
  #   container_name: postgres-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: fit_hub
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-net
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U postgres" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5


networks:
  app-net:
    driver: bridge

volumes:
  platform_postgres_data:
  bank_manager_postgres_data:
  minio_data: