// <auto-generated />
using System;
using FitHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitHub.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251019105640_AddBrands")]
    partial class AddBrands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentGym", b =>
                {
                    b.Property<Guid>("EquipmentsId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipments_id");

                    b.Property<Guid>("GymsId")
                        .HasColumnType("uuid")
                        .HasColumnName("gyms_id");

                    b.HasKey("EquipmentsId", "GymsId")
                        .HasName("pk_equipment_gym");

                    b.HasIndex("GymsId")
                        .HasDatabaseName("ix_equipment_gym_gyms_id");

                    b.ToTable("equipment_gym", (string)null);
                });

            modelBuilder.Entity("EquipmentInstructionMuscleGroup", b =>
                {
                    b.Property<Guid>("EquipmentInstructionId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_instruction_id");

                    b.Property<Guid>("MuscleGroupsId")
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_groups_id");

                    b.HasKey("EquipmentInstructionId", "MuscleGroupsId")
                        .HasName("pk_equipment_instruction_muscle_group");

                    b.HasIndex("MuscleGroupsId")
                        .HasDatabaseName("ix_equipment_instruction_muscle_group_muscle_groups_id");

                    b.ToTable("equipment_instruction_muscle_group", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brand");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalDescroption")
                        .HasColumnType("text")
                        .HasColumnName("additional_descroption");

                    b.Property<Guid>("BrandId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("InstructionAddBefore")
                        .HasColumnType("date")
                        .HasColumnName("instruction_add_before");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_equipment_brand_id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.EquipmentInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalDescription")
                        .HasColumnType("text")
                        .HasColumnName("additional_description");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EquipmentId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_equipment_instruction");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_equipment_instruction_equipment_id");

                    b.ToTable("equipment_instruction", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_gym");

                    b.ToTable("gym", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.GymZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_gym_zone");

                    b.ToTable("gym_zone", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Files.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<int?>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s3key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_file_entity");

                    b.ToTable("file_entity", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.BaseGroupTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer")
                        .HasColumnName("complexity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("TypeId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_base_group_trainings");

                    b.ToTable("base_group_trainings", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.GroupTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseGroupTrainingId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("base_group_training_id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TrainerId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.HasKey("Id")
                        .HasName("pk_group_training");

                    b.HasIndex("BaseGroupTrainingId")
                        .HasDatabaseName("ix_group_training_base_group_training_id");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("ix_group_training_trainer_id");

                    b.ToTable("group_training", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.MuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid?>("VideoTrainingId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_training_id");

                    b.HasKey("Id")
                        .HasName("pk_muscle_group");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_muscle_group_parent_id");

                    b.HasIndex("VideoTrainingId")
                        .HasDatabaseName("ix_muscle_group_video_training_id");

                    b.ToTable("muscle_group", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.PersonalTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TrainerId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.Property<Guid>("VisitorId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("pk_personal_training");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("ix_personal_training_trainer_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_personal_training_visitor_id");

                    b.ToTable("personal_training", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.TrainingType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_training_type");

                    b.ToTable("training_type", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.VideoTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer")
                        .HasColumnName("complexity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TrainingTypeId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("training_type_id");

                    b.HasKey("Id")
                        .HasName("pk_video_trainings");

                    b.HasIndex("TrainingTypeId")
                        .HasDatabaseName("ix_video_trainings_training_type_id");

                    b.ToTable("video_trainings", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Users.GymAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_gym_admin");

                    b.ToTable("gym_admin", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Users.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trainer");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trainer_user_id");

                    b.ToTable("trainer", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("FitHub.Domain.Users.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_visitor");

                    b.ToTable("visitor", (string)null);
                });

            modelBuilder.Entity("GroupTrainingVisitor", b =>
                {
                    b.Property<Guid>("GroupTrainingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_trainings_id");

                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uuid")
                        .HasColumnName("participants_id");

                    b.HasKey("GroupTrainingsId", "ParticipantsId")
                        .HasName("pk_group_training_visitor");

                    b.HasIndex("ParticipantsId")
                        .HasDatabaseName("ix_group_training_visitor_participants_id");

                    b.ToTable("group_training_visitor", (string)null);
                });

            modelBuilder.Entity("GymGymAdmin", b =>
                {
                    b.Property<Guid>("AdminsId")
                        .HasColumnType("uuid")
                        .HasColumnName("admins_id");

                    b.Property<Guid>("GymsId")
                        .HasColumnType("uuid")
                        .HasColumnName("gyms_id");

                    b.HasKey("AdminsId", "GymsId")
                        .HasName("pk_gym_gym_admin");

                    b.HasIndex("GymsId")
                        .HasDatabaseName("ix_gym_gym_admin_gyms_id");

                    b.ToTable("gym_gym_admin", (string)null);
                });

            modelBuilder.Entity("GymGymZone", b =>
                {
                    b.Property<Guid>("GymsId")
                        .HasColumnType("uuid")
                        .HasColumnName("gyms_id");

                    b.Property<Guid>("ZonesId")
                        .HasColumnType("uuid")
                        .HasColumnName("zones_id");

                    b.HasKey("GymsId", "ZonesId")
                        .HasName("pk_gym_gym_zone");

                    b.HasIndex("ZonesId")
                        .HasDatabaseName("ix_gym_gym_zone_zones_id");

                    b.ToTable("gym_gym_zone", (string)null);
                });

            modelBuilder.Entity("EquipmentGym", b =>
                {
                    b.HasOne("FitHub.Domain.Equipments.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_gym_equipment_equipments_id");

                    b.HasOne("FitHub.Domain.Equipments.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_gym_gym_gyms_id");
                });

            modelBuilder.Entity("EquipmentInstructionMuscleGroup", b =>
                {
                    b.HasOne("FitHub.Domain.Equipments.EquipmentInstruction", null)
                        .WithMany()
                        .HasForeignKey("EquipmentInstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_instruction_muscle_group_equipment_instruction_eq");

                    b.HasOne("FitHub.Domain.Trainings.MuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("MuscleGroupsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_instruction_muscle_group_muscle_group_muscle_grou");
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.Equipment", b =>
                {
                    b.HasOne("FitHub.Domain.Equipments.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_brand_brand_id");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.EquipmentInstruction", b =>
                {
                    b.HasOne("FitHub.Domain.Equipments.Equipment", "Equipment")
                        .WithMany("Instructions")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_instruction_equipment_equipment_id");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.GroupTraining", b =>
                {
                    b.HasOne("FitHub.Domain.Trainings.BaseGroupTraining", "BaseGroupTraining")
                        .WithMany()
                        .HasForeignKey("BaseGroupTrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_training_base_group_trainings_base_group_training_id");

                    b.HasOne("FitHub.Domain.Users.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_training_trainer_trainer_id");

                    b.Navigation("BaseGroupTraining");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.MuscleGroup", b =>
                {
                    b.HasOne("FitHub.Domain.Trainings.MuscleGroup", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_muscle_group_muscle_group_parent_id");

                    b.HasOne("FitHub.Domain.Trainings.VideoTraining", null)
                        .WithMany("MuscleGroups")
                        .HasForeignKey("VideoTrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_muscle_group_video_trainings_video_training_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.PersonalTraining", b =>
                {
                    b.HasOne("FitHub.Domain.Users.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_personal_training_trainer_trainer_id");

                    b.HasOne("FitHub.Domain.Users.Visitor", "Visitor")
                        .WithMany("PersonalTrainings")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_personal_training_visitor_visitor_id");

                    b.Navigation("Trainer");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.VideoTraining", b =>
                {
                    b.HasOne("FitHub.Domain.Trainings.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_video_trainings_training_type_training_type_id");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("FitHub.Domain.Users.Trainer", b =>
                {
                    b.HasOne("FitHub.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupTrainingVisitor", b =>
                {
                    b.HasOne("FitHub.Domain.Trainings.GroupTraining", null)
                        .WithMany()
                        .HasForeignKey("GroupTrainingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_training_visitor_group_training_group_trainings_id");

                    b.HasOne("FitHub.Domain.Users.Visitor", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_training_visitor_visitor_participants_id");
                });

            modelBuilder.Entity("GymGymAdmin", b =>
                {
                    b.HasOne("FitHub.Domain.Users.GymAdmin", null)
                        .WithMany()
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_gym_admin_gym_admin_admins_id");

                    b.HasOne("FitHub.Domain.Equipments.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_gym_admin_gym_gyms_id");
                });

            modelBuilder.Entity("GymGymZone", b =>
                {
                    b.HasOne("FitHub.Domain.Equipments.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_gym_zone_gym_gyms_id");

                    b.HasOne("FitHub.Domain.Equipments.GymZone", null)
                        .WithMany()
                        .HasForeignKey("ZonesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_gym_zone_gym_zone_zones_id");
                });

            modelBuilder.Entity("FitHub.Domain.Equipments.Equipment", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("FitHub.Domain.Trainings.VideoTraining", b =>
                {
                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("FitHub.Domain.Users.Visitor", b =>
                {
                    b.Navigation("PersonalTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
