version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - file-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet_rabbit_demo
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - file-network

volumes:
  rabbitmq_data:
  
  
networks:
  file-network:
    driver: bridge