// <auto-generated />
using System;
using FitHub.BankManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitHub.BankManager.Data.Migrations
{
    [DbContext(typeof(BankManagerDataContext))]
    partial class BankManagerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitHub.BankManager.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bank_accounts");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_accounts_name");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.BankWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_event_id");

                    b.Property<string>("Payload")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("payload");

                    b.Property<Guid>("PaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bank_webhook_events");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_webhook_events_external_event_id");

                    b.HasIndex("PaymentIntentId")
                        .HasDatabaseName("ix_bank_webhook_events_payment_intent_id");

                    b.ToTable("bank_webhook_events", (string)null);
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BankAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_reference");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payment_intents");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("ix_payment_intents_bank_account_id");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("ix_payment_intents_external_reference");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_intents_idempotency_key");

                    b.ToTable("payment_intents", (string)null);
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.PaymentOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_event_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("PaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_payment_operations");

                    b.HasIndex("ExternalEventId")
                        .HasDatabaseName("ix_payment_operations_external_event_id");

                    b.HasIndex("PaymentIntentId")
                        .HasDatabaseName("ix_payment_operations_payment_intent_id");

                    b.ToTable("payment_operations", (string)null);
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.RabbitOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("exchange_name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("routing_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rabbit_outbox_messages");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_rabbit_outbox_messages_status_created_at");

                    b.ToTable("rabbit_outbox_messages", (string)null);
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.BankWebhookEvent", b =>
                {
                    b.HasOne("FitHub.BankManager.Domain.PaymentIntent", "PaymentIntent")
                        .WithMany()
                        .HasForeignKey("PaymentIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bank_webhook_events_payment_intents_payment_intent_id");

                    b.Navigation("PaymentIntent");
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.PaymentIntent", b =>
                {
                    b.HasOne("FitHub.BankManager.Domain.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_intents_bank_accounts_bank_account_id");

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.PaymentOperation", b =>
                {
                    b.HasOne("FitHub.BankManager.Domain.PaymentIntent", "PaymentIntent")
                        .WithMany("Operations")
                        .HasForeignKey("PaymentIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_operations_payment_intents_payment_intent_id");

                    b.Navigation("PaymentIntent");
                });

            modelBuilder.Entity("FitHub.BankManager.Domain.PaymentIntent", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
